### ISSUE TITLE
Add google analytics code

### ISSUE THREAD

**Issue by callummac88** [callummac88/ibf#4]

**Comment by mkaf89** [comment]
GA code- 

UA-61824968-1

**Comment by mkaf89** [comment]
Has this been complete?

**Comment by callummac88** [comment]
did you set up your own google account for this or do you need me to it same as BBF?

**Comment by mkaf89** [comment]
I set up my own code above. Think it was easier as it gives me full admin so I can set-up e-commerce tracking on the ticket sales etc

**Comment by callummac88** [comment]
ah never noticed that, cool will add that in asap.
